# Cocioran Stefan 321CA

CFLAGS = g++ -std=c++11 -g -Werror -Wall

all: server subscriber

# Compileaza server.cpp
server: server.cpp

# Compileaza subscriber.cpp
subscriber: subscriber.cpp

clean:
	rm -f server subscriber
